# Generated by Django 2.0.1 on 2019-05-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0002_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='coment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
