# Generated by Django 2.0.1 on 2019-05-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0003_comment_coment'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('btype', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
