# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-07 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='brief',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
