# Generated by Django 2.0.1 on 2019-05-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0005_book_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
