# Generated by Django 2.0.1 on 2019-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0006_user_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('userhead', models.CharField(max_length=100)),
                ('bookid', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('coment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='booklike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('bookid', models.CharField(max_length=100)),
            ],
        ),
    ]
