# Generated by Django 2.0.1 on 2019-05-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0007_bookcomment_booklike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomment',
            name='userhead',
        ),
        migrations.RemoveField(
            model_name='bookcomment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='bookideal',
            name='userhead',
        ),
        migrations.RemoveField(
            model_name='bookideal',
            name='username',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userhead',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
