# Generated by Django 2.0.1 on 2019-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0008_auto_20190509_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userhead',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
    ]
